I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 193, in script
    python:
  File "renpy/common/00start.rpy", line 194, in <module>
    renpy.execute_default_statement(True)
  File "game/screens.rpy", line 267, in execute_default
    default quick_menu = True
Exception: store.quick_menu is being given a default a second time.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 193, in script
    python:
  File "C:\Users\Greshnick\Desktop\renpy-8.2.0-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Greshnick\Desktop\renpy-8.2.0-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 194, in <module>
    renpy.execute_default_statement(True)
  File "C:\Users\Greshnick\Desktop\renpy-8.2.0-sdk\renpy\exports.py", line 4090, in execute_default_statement
    i.execute_default(start)
  File "game/screens.rpy", line 267, in execute_default
    default quick_menu = True
Exception: store.quick_menu is being given a default a second time.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
VisualNovelRenPy 1.0
Tue Feb 13 16:25:46 2024
